# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2e555bf07b7d2948a88748e9d019e1ab2a40b94c1fdb83165d29746a1adb2a312df2740accd9d8353f53aa231ae6da919796430e0ce3d67e822047e5b70de6

test:
  secret_key_base: 4d5b68a951c43b7fd4aed8c815d148d53f807d8a5863fa097dd153e2a798567947dae05acaf37f80e6452014d1822bdfdefcebe20c96eed29d61910ef6cd8635

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
